- name: Set MacOS system settings
  become: true
  shell: "{{ ansible_env.DOTFILES_REPO }}/scripts/macos.sh"
  tags:
    - never
    - init

- name: Copy VS Code options
  synchronize:
    delete: false
    src: "{{ ansible_env.DOTFILES_REPO }}/vscode/"
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/"

